
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/kevin/Projects/cvops/cvops-python/venv/lib/python3.10/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.2.0-37-generic - x86_64
...
