
name: Build, Test, Release
on: [push, pull_request]
jobs:
  lint:
    name: Lint Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Virtual Environment
        uses: ./.github/actions/install_virtualenv
        with:
          python-version: "3.10"
      - name: Run linter
        run: |
          source venv/bin/activate
          lint

  test:
    name: Test Python
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Virtual Environment
        uses: ./.github/actions/install_virtualenv
        with:
          python-version: "3.10"
      - name: Run tests
        run: |
          source venv/bin/activate
          run_tests

        

